### ISSUE TITLE
Page freeze with 100% CPU load when (at least 2 of) slides doesn't have id prop

### ISSUE THREAD

**Issue by tehnolog** [Valexr/svelte-slidy#18]
I think there's 2 options:

1. Make `id` prop not mandatory. Maybe create default internal id's based on array index (slides is an Array anyway).
2. Handle this case and just throw an error with notice. Add note about this in docs.

**Comment by axmad386** [comment]
I just read the Slidy Component, I think this is because Slidy loop slides with hardcoded item.id as key. May be we can add something like keyExtractor as function to extract which key to become id and add fallback to index when there is no id key or keyExtractor not set.
``` svelte
{#each slides as item, i (item.id)}
```
may be we can change to this
``` svelte
<script>
export let keyExtractor = (item)=>item.id
</script>
{#each slides as item, i (keyExtractor(item)||i)}
```
I can make PR if necessary

**Comment by axmad386** [comment]
I am not tested the code yet, but I think it's should work

**Comment by Valexr** [comment]
merged
